export default {
  login: "kolibriof",
  id: 122736279,
  node_id: "U_kgDOB1DOlw",
  avatar_url: "https://avatars.githubusercontent.com/u/122736279?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/kolibriof",
  html_url: "https://github.com/kolibriof",
  followers_url: "https://api.github.com/users/kolibriof/followers",
  following_url:
    "https://api.github.com/users/kolibriof/following{/other_user}",
  gists_url: "https://api.github.com/users/kolibriof/gists{/gist_id}",
  starred_url: "https://api.github.com/users/kolibriof/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/kolibriof/subscriptions",
  organizations_url: "https://api.github.com/users/kolibriof/orgs",
  repos_url: "https://api.github.com/users/kolibriof/repos",
  events_url: "https://api.github.com/users/kolibriof/events{/privacy}",
  received_events_url: "https://api.github.com/users/kolibriof/received_events",
  type: "User",
  site_admin: false,
  name: "Dima Savchenko",
  company: "SoftServe",
  blog: "kolibriof.com",
  location: "Wroclaw",
  email: "kolibri380@gmail.com",
  hireable: null,
  bio: "Hello and Welcome to my new project!",
  twitter_username: "kolibri",
  public_repos: 5,
  public_gists: 0,
  followers: 1337,
  following: 777,
  created_at: "2023-01-15T14:47:51Z",
  updated_at: "2023-05-02T15:11:55Z",
};
